// <auto-generated />
using CarsSpring2024.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarsSpring2024.Migrations
{
    [DbContext(typeof(CarsDbContext))]
    [Migration("20240227064330_AddingModelsTableAndSeedData")]
    partial class AddingModelsTableAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarsSpring2024.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CarId");

                    b.HasIndex("MakeId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            MakeId = 1,
                            Model = "Camry",
                            Price = 25000m
                        },
                        new
                        {
                            CarId = 2,
                            MakeId = 2,
                            Model = "F-150",
                            Price = 69000m
                        },
                        new
                        {
                            CarId = 3,
                            MakeId = 3,
                            Model = "Civic",
                            Price = 20000m
                        });
                });

            modelBuilder.Entity("CarsSpring2024.Models.Make", b =>
                {
                    b.Property<int>("MakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MakeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MakeId");

                    b.ToTable("Makes");

                    b.HasData(
                        new
                        {
                            MakeId = 1,
                            Description = "This is a description for Toyota.",
                            Name = "Toyota"
                        },
                        new
                        {
                            MakeId = 2,
                            Description = "This is the description for Ford",
                            Name = "Ford"
                        },
                        new
                        {
                            MakeId = 3,
                            Description = "This is the description for Honda",
                            Name = "Honda"
                        });
                });

            modelBuilder.Entity("CarsSpring2024.Models.Car", b =>
                {
                    b.HasOne("CarsSpring2024.Models.Make", "Make")
                        .WithMany()
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Make");
                });
#pragma warning restore 612, 618
        }
    }
}
