// <auto-generated />
using CarsSpring2024.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarsSpring2024.Migrations
{
    [DbContext(typeof(CarsDbContext))]
    [Migration("20240226204753_CreatingMakesTableAndSeeding")]
    partial class CreatingMakesTableAndSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarsSpring2024.Models.Make", b =>
                {
                    b.Property<int>("MakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MakeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MakeId");

                    b.ToTable("Makes");

                    b.HasData(
                        new
                        {
                            MakeId = 1,
                            Description = "This is a description for Toyota.",
                            Name = "Toyota"
                        },
                        new
                        {
                            MakeId = 2,
                            Description = "This is the description for Ford",
                            Name = "Ford"
                        },
                        new
                        {
                            MakeId = 3,
                            Description = "This is the description for Honda",
                            Name = "Honda"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
